### ISSUE TITLE
How to get only the id of the relationships when request to */{id}/relationships/* ?

### ISSUE THREAD

**Issue by a-wf** [scoutforpets/jsonapi-mapper#105]
Hi, 

My work is based on JsonApi spec. Currently, I am implementing the relationships paths of my server api, I am trying to get response format like : https://jsonapi.org/format/#fetching-relationships.

However I don't know how to remove the attributes part of the data field to get only the type and the id of each target items. 

Could you help me? 

Thank you

**Comment by chamini2** [comment]
Well, if you are looking for a regex that gets the `id` form `relationships` urls, I think this works:

```
/\/([^\/]+)\/relationships\//
```


For example, in node:

```
> /\/([^\/]+)\/relationships\//.exec("/articles/1/relationships/comments")
[ '/1/relationships/',
  '1',
  index: 9,
  input: '/articles/1/relationships/comments',
  groups: undefined ]
```

As you can see, the index 1 has the matched patter, `'1'`

**Comment by a-wf** [comment]
Hi @chamini2 
That's not what I was looking for, but thanks !

What I wanted is just to query the data with bookshelf and to retrieve only the 'id' of the queried data.  Then by parsing with jsonapi-mapper, to get data without attributes like: 
```
  "data": [
    { "type": "tags", "id": "2" },
    { "type": "tags", "id": "3" }
  ]
``` 


Finally, I success to do this by using knex queryBuilder.select('id').innerJoin(...)  then jsonapi-mapper parsing with option attributes omit 'id'
