### ISSUE TITLE
nested relations only work when the nested relationship is a one-to

### ISSUE THREAD

**Issue by jamesdixon** [scoutforpets/jsonapi-mapper#33]
Discovered an issue that when trying to access a nested relationship, such as `project.tasks` where `tasks` is a `many` relation, the result is not properly mapped. It only works for something like `project.user` where `user` is a `one-to` relation.

Looking at the code, the issue is obvious and it's a fairly easy fix. However, analyzing the code further shows there is quite a bit of duplication in the `map()` method. It's only a slightly different case when the we're dealing with a `Collection` or a `Model`. I believe this can be refactored to be a recursive function that should reduce the amount of code, solve the issues with dealing with `Collection` vs. `Model` and even support very deep nesting of relations rather than a single level.

@ShadowManu any thoughts?

**Comment by ShadowManu** [comment]
Are you thinking on starting the recursion on the original `data`, or the `relations` of each object? Either way, I think its possible but needs care (I personally don't remember at this point how `Serializer` treats deep stuff. Do you have a rough pseudo-code on it? This could take time, but the test harness helps a lot.

**Comment by jamesdixon** [comment]
I haven't worked up any pseudo-code or dove too deep into this, but my initial thought was starting recursion on the original data, but it might have to be on the relations. Either way, it seems like there is an opportunity to simplify things.

**Comment by ShadowManu** [comment]
If I find some free time, I will focus first on making tests shorter. Files over 400 lines are not my most loved thing ;)
