### ISSUE TITLE
support for disabling links

### ISSUE THREAD

**Issue by jamesdixon** [scoutforpets/jsonapi-mapper#34]
According to the spec, links are optional. In practice, I haven't seen much that takes advantage of them. For example, I'm using Ember on the frontend and Ember Data does have some support, but it seems to be extremely limited even though it's listed as one of the gold standards as far as implementations go.

That said, I believe it might be good to offer an option to enable/disable links. Slight performance boost and definitely some savings in terms of payload size.

@ShadowManu @jcao02 thoughts? Are links something you're taking advantage of?

**Comment by ShadowManu** [comment]
Not really right now, but there's been discussions of using it as a
discoverability tool to autogenerate services on Angular. But I agree on
the points to provide disabling them.

On Fri, May 13, 2016 at 9:45 PM James Dixon <notifications@github.com>
wrote:

> According to the spec, links are optional. In practice, I haven't seen
> much that takes advantage of them. For example, I'm using Ember on the
> frontend and Ember Data does have some support, but it seems to be
> extremely limited even though it's listed as one of the gold standards as
> far as implementations go.
>
> That said, I believe it might be good to offer an option to enable/disable
> links. Slight performance boost and definitely some savings in terms of
> payload size.
>
> @ShadowManu <https://github.com/ShadowManu> @jcao02
> <https://github.com/jcao02> thoughts? Are links something you're taking
> advantage of?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/scoutforpets/jsonapi-mapper/issues/34>
>
-- 
Manuel Pacheco
Estudiante de Ingeniería en Computación - Computer Engineer Student
Universidad Simón Bolívar
