### ISSUE TITLE
Virtual properties are not mapped

### ISSUE THREAD

**Issue by kwelch2015** [scoutforpets/jsonapi-mapper#35]
When sending in a bookshelf model to map where there are virtual properties added (using the [Virtuals](https://github.com/tgriesser/bookshelf/wiki/Plugin:-Virtuals) plugin) the mapper ignores them.  I have a fix for util.ts that will check for the presence of virtual properties and when the virtual properties are marked visible they will get added to the attributes that will be part of the JSONAPI payload returned.

**Comment by jamesdixon** [comment]
Thanks for reporting this. I'm not using any virtual properties currently, so completely missed this. Would you mind submitting a PR?

Cheers!

**Comment by jamesdixon** [comment]
@kwelch2015 you mentioned that you have a fix for this: would you mind submitting a PR?

**Comment by jamesdixon** [comment]
@chamini2 would be good to fix this and #76 given that they're both core bookshelf plugins
