### ISSUE TITLE
toJSON is recursive on relations, template generation is not.

### ISSUE THREAD

**Issue by ralfschimmel** [scoutforpets/jsonapi-mapper#40]
Currently the template builder does not support withRelated properties which go deeper then one relation.

`this.that` works, but `this.that.andthat` does not.

It seems to me https://github.com/scoutforpets/jsonapi-mapper/blob/master/src/bookshelf/mapper.ts#L122-L138 should become recursive, correct me if I'm wrong. I can have a swing at it and make a PR if you agree this is what needs to happen.

**Comment by jamesdixon** [comment]
@ralfschimmel agreed! I believe recursion could be applied in other areas too. `toJSON` was just refactored to take advantage of recursion. Would certainly appreciate any help if making this tidier! I am going to push out a new release in a few minutes, so you may want to wait until that's done before submitting a PR. I'll ping you when it's done. Thanks!

**Comment by ralfschimmel** [comment]
My first attempt at typescript, but it seems to work. 
https://github.com/scoutforpets/jsonapi-mapper/pull/42
