### ISSUE TITLE
Fix mapRelations nested links and specs

### ISSUE THREAD

**Issue by chamini2** [scoutforpets/jsonapi-mapper#45]
The PR #42 added a recursive function `mapRelations` to handle nested relations, but is not correctly tested and also behaves incorrectly for the generated links in the nested relations; we need to either fix the links for nested relations or remove them.

Also, this functions needs to be tested, since the specs currently don't cover it thoroughly.

**Comment by jamesdixon** [comment]
@chamini2 @ShadowManu will this be resolved in #47?

**Comment by ShadowManu** [comment]
tests like [this one](https://github.com/scoutforpets/jsonapi-mapper/blob/refactor/spec/bookshelf-spec.ts#L561) covers for link generation, and the tests pass. I'll go ahead of the release and close this.
