### ISSUE TITLE
deprecate includeRelations in Bookshelf mapper

### ISSUE THREAD

**Issue by ShadowManu** [scoutforpets/jsonapi-mapper#46]
I'm working on a refactor of the mapper and I see again the `includeRelations` option, left as a compatible (but deprecated) option. Is it still needed to support this @jamesdixon? Or can it finally die in peace ;)?

**Comment by jamesdixon** [comment]
RIP includeRelations ☠

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Tue, Jul 5, 2016 at 6:40 PM, Manuel Pacheco <notifications@github.com> wrote:
I'm working on a refactor of the mapper and I see again the includeRelations option, left as a compatible (but deprecated) option. Is it still needed to support this @jamesdixon [https://github.com/jamesdixon] ? Or can it finally die in peace ;)?

**Comment by ShadowManu** [comment]
Gotcha. Will keep working ;)
