### ISSUE TITLE
Missing _id properties

### ISSUE THREAD

**Issue by confuser** [scoutforpets/jsonapi-mapper#52]
I have an attribute named player_id. In this particular instance, it shouldn't have a relationship and should simply be output into the attributes property.

The response from the mapper doesn't contain it.

It looks like anything that ends with `_id` is being explicitly left out https://github.com/scoutforpets/jsonapi-mapper/blob/v0.9.0/src/bookshelf/utils.ts#L49

Is there a way to disable this behaviour, or at least mark fields to ignore? Current work around is to map the data, and reattach the missing attribute manually.

Looks like this came up in #23

**Comment by jamesdixon** [comment]
@confuser can you provide a sample response so I can better understand the issue?

**Comment by confuser** [comment]
Expected response:

```json
{
  "links": {
    "self": "http://localhost:60990/player-bans"
  },
  "data": {
    "type": "player-ban",
    "id": "9e13f332-158",
    "links": {
      "self": "http://localhost:60990/player-bans/9e13f332-158"
    },
    "attributes": {
      "reason": "Hello",
      "created": 1454076266,
      "updated": 1454076266,
      "expires": 0,
      "player_id": "e86c3453-d603-4085-ab71-45c7f1a44edd"
    },
    "relationships": {
      "server": {
        "data": {
          "type": "server",
          "id": "9e13f332"
        }
      },
      "actor": {
        "data": {
          "type": "player",
          "id": "ae51c849-3f2a-4a37-986d-55ed5b02307f"
        }
      }
    }
  }
}
```

Actual response:
```json
{
  "links": {
    "self": "http://localhost:60990/player-bans"
  },
  "data": {
    "type": "player-ban",
    "id": "9e13f332-158",
    "links": {
      "self": "http://localhost:60990/player-bans/9e13f332-158"
    },
    "attributes": {
      "reason": "Hello",
      "created": 1454076266,
      "updated": 1454076266,
      "expires": 0
    },
    "relationships": {
      "server": {
        "data": {
          "type": "server",
          "id": "9e13f332"
        }
      },
      "actor": {
        "data": {
          "type": "player",
          "id": "ae51c849-3f2a-4a37-986d-55ed5b02307f"
        }
      }
    }
  }
}
```

Note the missing `player_id` property within attributes

**Comment by jamesdixon** [comment]
@confuser the actual response is valid. If you take a look at [the spec](http://jsonapi.org/format/#document-resource-object-identification), it says the following:

> Although has-one foreign keys (e.g. author_id) are often stored internally alongside other information to be represented in a resource object, these keys SHOULD NOT appear as attributes.

**Comment by ShadowManu** [comment]
@confuser is this still an important use case for you?

**Comment by confuser** [comment]
I worked around it in the end. My use case is probably more of an edge case. The id in question has no benefit to the consuming system other than displaying it. Trying to adhere to the spec by moving it to a relationship was rather convoluted to then display simply the id in Ember.

Happy to close this as understandably it seems this module's goal is to keep in line with the specification.

**Comment by jamesdixon** [comment]
@confuser going to close this based on your last comment. Thank you for your contributions!
