### ISSUE TITLE
stringifying json with circular dependencies

### ISSUE THREAD

**Issue by jamesdixon** [scoutforpets/jsonapi-mapper#55]
I ran into an issue where data I received from an external API contained circular references, which throws an error when stringifying. Normally, this could be resolved by using something like [fast-safe-stringify](https://github.com/davidmarkclements/fast-safe-stringify), but given that we have our own method of converting to JSON, this may be not be an option. I haven't investigated in any depth, but wanted to bring it up.

**Comment by jamesdixon** [comment]
@chamini2 in regards to your comment in #47, you're correct. In most cases, I think this probably isn't going to be an issue. We'll mark it as an enhancement/help-wanted.

**Comment by chamini2** [comment]
@jamesdixon, can we close this one? I don't think this is or will be a problem.

**Comment by jamesdixon** [comment]
@chamini2 agreed!
