### ISSUE TITLE
Mapper removes attributes that end in `type` and `id`

### ISSUE THREAD

**Issue by chamini2** [scoutforpets/jsonapi-mapper#56]
I understand this is intended behaviour, but shouldn't there be an option to pass attributes to **not** be omitted from the output?

Another property in the `mapperOptions` param like `{ keepAttributes: ['keep_type', 'thing-id'] }`

**Comment by ShadowManu** [comment]
Closing by the same reasons as stated in #52.

**Comment by chamini2** [comment]
I understand that in #52 the submitter was ok with not adding this functionality. But shouldn't we make this an option, it seems to be a good idea.

**Comment by ShadowManu** [comment]
But then the result is NOT jsonapi compliant.

**Comment by jamesdixon** [comment]
While I understand the edge case, I think it's best that we stick to the spec. Otherwise, adding custom options could get out of control :)

**Comment by chamini2** [comment]
The usual case for an attribute to be called `something_id` is because it refers to a relationship to another resource; this is the case in which the [spec](http://jsonapi.org/format/#document-resource-object-attributes) advises to **not** included these attributes.

But, in the case where an attribute has `_id` or `_type` in the name but is not a relationship (think of `document_id` to represent the ID document for a country), we should be allowed to include it in the payload, since it doesn't represent a relationship.

**Comment by chamini2** [comment]
Another case to consider is relationships that use an attribute that doesn't end in `id` or `type`. As an example, we have a relation through the attribute `avatar` and have to then drop it from the output of the mapper.

This one is harder to specify as an option because we could be meaning to drop an attribute for certain relation only.

**Comment by chamini2** [comment]
closed by #72
