### ISSUE TITLE
1.0 API

### ISSUE THREAD

**Issue by jamesdixon** [scoutforpets/jsonapi-mapper#59]
**Synopsis**
Discuss pros, cons and implementation of our own API that will prevent changes in the underlying serializer API from affecting the mapper.

See #57 for further discussion on this topic.

**Comment by chamini2** [comment]
Well, some pros and cons I can come up with right now

PROS:
- Not depending on another project's API, just it's functionality
- Full documentation of the tool's capabilities (#30 was opened for not knowing the solution of using the serializer's API)
- Achieving a high-level abstraction ([scond paragraph](https://github.com/scoutforpets/jsonapi-mapper/issues/57#issuecomment-240265414))

CONS:
- Maintaining a larger code base

**Comment by jamesdixon** [comment]
Based on a conversation w/ @chamini2, we'd like to finalize the API in the next beta and then release 1.0. We had specifically discussed our public API and how that maps to the serializer options. 

**Proposal**
* `typeForModel` - relates to the `type` returned in the payload. This would map to the `typeForAttribute` option in the serializer. `typeForModel` seems to make more sense than `typeForAttribute`. It would accept a function or an object containing relation/type mappings. By default, we would pass our own function that would pluralize the type.

* `keyForAttribute` - this would be a one-to-one mapping to the `keyForAttribute` function in the serializer.

Thoughts on this?

cc: @ShadowManu @jcao02 @chamini2

**Comment by chamini2** [comment]
Agreed with everything.

**Comment by jcao02** [comment]
Agree

**Comment by ShadowManu** [comment]
Not going to disagree and be the party crasher ;) Only thing (also a question) would be to make clear on the documentation if the `typeforModel` affects the main model/collection (it doesn't, right?).

**Comment by jamesdixon** [comment]
@ShadowManu but you sound like you're itching to disagree! 😄 

As for your question, `typeForModel` would affect the type of the model. Maybe I'm misunderstanding the quest?

**Comment by chamini2** [comment]
I think he meant we should specify that `typeForModel` only specifies types for relations' models, not the main one.

**Comment by jamesdixon** [comment]
Gotcha. Thanks for clarifying.

**Comment by jamesdixon** [comment]
@chamini2 can we close this given your PR from a few days back?

**Comment by chamini2** [comment]
Sure, I had forgotten
