### ISSUE TITLE
options for serializing relationships

### ISSUE THREAD

**Issue by jamesdixon** [scoutforpets/jsonapi-mapper#63]
Currently, we have a method to completely disable the serialization AND inclusion of relationships via the `relations` property. However, this option only affects whether or not relations are `included` in the payload; it's either all or nothing. We have no public API for serialization of the relationships, but not including the actual related resources as part of the payload. This can be done by passing `included: false` to the serializer directly, but it needs to be passed as a property of the relationship itself. Currently, this doesn't work properly because we pass all `serializerOptions` at the root level.

This is both a bug and an opportunity to define a public API as to whether or not relationships are included as part of the payload.

My suggestion for the API:

* `relations` - this property would remain the same and would strictly affect whether or not relations are serialized as part of the payload, either as linkage or included.
* `includeRelations` - this property affects whether or not the relations are included as a compound document (embedded).

Scenarios:

**Relationships enabled and included**
* `relations: true`
* `includeRelations: true`

```js
{
  "included": [
    {
      "type": "pet",
      "id": "60",
      "attributes": {
        "name": "Toney"
    }
  ],
  "data": {
    "type": "customer",
    "id": "37",
    "attributes": {
      "firstName": "Peter",
      "lastName": "Fritsch"
    },
    "relationships": {
      "pets": {
        "data": [
          {
            "type": "pet",
            "id": "60"
          }
        ]
      }
    }
  }
}
```

**Relationships enabled and NOT included**
* `relations: true`
* `includeRelations: false`

```js
{
  "data": {
    "type": "customer",
    "id": "37",
    "attributes": {
      "firstName": "Peter",
      "lastName": "Fritsch"
    },
    "relationships": {
      "pets": {
        "data": [
          {
            "type": "pet",
            "id": "60"
          }
        ]
      }
    }
  }
}
```

**Relationships disabled**
* `relations: false`
* `includeRelations: false` (has no effect)

```js
{
  "data": {
    "type": "customer",
    "id": "37",
    "attributes": {
      "firstName": "Peter",
      "lastName": "Fritsch"
    }
  }
}
```

@chamini2 @ShadowManu thoughts? I'm going to start working on this now as it's something I need to implement, but open to changes.

**Comment by chamini2** [comment]
What about wanting some relations included and some relations not included? It's not currently a scenario for us, but is it worth thinking about?

**Comment by jamesdixon** [comment]
Certainly a possibility. I'd probably opt to start with this and make any enhancements if we get feedback that indicates it as something that's needed.

**Comment by chamini2** [comment]
Yes, you're probably right. I'll say it looks good to implement.

Another option would be to merge both options in one:

```
relations : true // all in
relations : false // nothing
relations : { included: true } // all in
relations : { included: false } // not included

**Comment by jamesdixon** [comment]
@chamini2 how would you also deal with specifying the relations to be serialized? 

Currently, I believe you can do something like `relations: ['rel1', 'rel2']`

**Comment by chamini2** [comment]
Yeah, that seems good @jamesdixon

**Comment by adnanoner** [comment]
Nice PR. What about an option to include relations as metadata per row, for example in case you have a one-on-one relationship? Maybe a bit too complicated/ambigue to add though.

**Comment by chamini2** [comment]
@adnanoner, I did not understand very well what you meant, but you are welcome to open an issue suggesting the feature!
