### ISSUE TITLE
mapper breaks bookshelf visibility plugin

### ISSUE THREAD

**Issue by jamesdixon** [scoutforpets/jsonapi-mapper#76]
The visibility plugin allows you to hide fields from the response (ex: password). Currently, it doesn't work with the mapper. Looks like it's part of the toJSON method, which we're overriding:

https://github.com/tgriesser/bookshelf/blob/master/src/plugins/visibility.js

**Comment by jamesdixon** [comment]
@chamini2 what do you think about getting this and #35 resolved for 1.0? Both are core bookshelf plugins.

**Comment by chamini2** [comment]
Agreed, we may be in beta for a little while 😄 .
