### ISSUE TITLE
Use in typescript project

### ISSUE THREAD

**Issue by codedoge** [scoutforpets/jsonapi-mapper#89]
Is there a way to use this library in a Typescript project?

**Comment by ShadowManu** [comment]
Funny thing we haven't updated with TS2 way to provide typings (and we never did with tsd or typings) . I'll make a PR fixing this today.

**Comment by ShadowManu** [comment]
@codedoge I've been working on it on #90. While we finish reviewing it, would you care to try using/testing it with `@shadowmanu/jsonapi-mapper@1.0.0-beta.10-2`?

**Comment by codedoge** [comment]
I'll take a look, it's the first time I use this lib and I don't have much experience with typescript. I'll try and let you know.

**Comment by ShadowManu** [comment]
Since PR #90 has been merged to `master` (waiting for next release), I'll be closing this.
