### ISSUE TITLE
problems with typeForModel

### ISSUE THREAD

**Issue by jamesdixon** [scoutforpets/jsonapi-mapper#92]
@ShadowManu @chamini2 have either of you successfully used the `typeForModel` option to change the type of a relation? For example, I have a relation `primaryStaff`, which needs to have a `type` of `staff`. I passed the following to the mapper:

```js
{
  typeForModel: {
    'primaryStaff': 'staff'
  }
}
```

but no luck.

**Comment by ShadowManu** [comment]
I have a long time without putting code in here, but [this test](https://github.com/scoutforpets/jsonapi-mapper/blob/master/spec/bookshelf-spec.ts#L1593) and consequent ones should verify it works.

**Comment by jamesdixon** [comment]
@ShadowManu same, but I saw the same test and while it should work, it doesn't appear to be. I'll look into it further.

**Comment by chamini2** [comment]
I have been using it a lot, @jamesdixon.

If I define a relation in Bookshelf like:

```js
Model.extend({
  provider() {
    return this.belongsTo('User');
  }
  // ...
});
```

I use it like:

```js
mapper.map(model, type, { typeForModel: {provider: 'users'} });
```

**Comment by jamesdixon** [comment]
@chamini2 thanks! I will double-check my usage.

**Comment by jamesdixon** [comment]
@chamini2 turns out that it's a bug. I use `typeForAttribute` to singularize my `type`s and that seems to be where the issue lies.

On another note, are we not camel-casing relationship names by default? I noticed that I removed my `keyForAttribute` function which was camelCasing relations, that everything is still camelCased!

**Comment by jamesdixon** [comment]
Ok, not so much a bug, but really a side-effect of using the serializer methods directly rather than `typeForModel`. I had never converted to using that method, but now that I have, things are working as intended.

Hope you all are doing well! Cheers.

**Comment by ShadowManu** [comment]
I would like to comment that I remember a discussion with Matteo where we noticed that effect: using `typeForAttribute` will negate `typeForModel`. Which is ok, but lacks documentation about it. Want to give some love to the readme? ;)
